// Generated by CoffeeScript 1.4.0
var Action, Lazy, ant, child_process, fs;

Lazy = require('lazy');

fs = require('fs');

child_process = require('child_process');

ant = require('./ant');

module.exports = Action = (function() {

  function Action() {}

  Action.writeLine = function(line) {
    return ant.writeLine('action '.yellow, ': '.bold.white + line);
  };

  Action.run = function(argv, file) {
    var lazy,
      _this = this;
    lazy = Lazy(fs.createReadStream(file));
    return lazy.lines.forEach(function(chunk) {
      var child, exec, line;
      if (!chunk) {
        return;
      }
      line = chunk.toString();
      if (line.match(/^\/\/noyd:onchange:exec/)) {
        exec = line.split('noyd:onchange:exec')[1];
        _this.writeLine('running: ' + exec.bold.white);
        child = child_process.spawn(exec);
        return child.stdout.on('data', function(data) {
          var buffer, _i, _len, _ref, _results;
          buffer = new Buffer(data);
          _ref = buffer.toString().split('\n');
          _results = [];
          for (_i = 0, _len = _ref.length; _i < _len; _i++) {
            line = _ref[_i];
            _results.push(_this.writeLine(line));
          }
          return _results;
        });
      }
    });
  };

  return Action;

})();
