// Generated by CoffeeScript 1.4.0
var Ant, child_process, colors, input, keypress, prompt;

child_process = require('child_process');

colors = require('colors');

keypress = require('keypress');

keypress(process.stdin);

prompt = '  task : '.bold.white;

input = '';

module.exports = Ant = (function() {

  function Ant() {}

  Ant.writeLine = function(context, line) {
    process.stdout.clearLine();
    process.stdout.cursorTo(0);
    console.log(context + line);
    return process.stdout.write(prompt + input);
  };

  Ant.ant = function(task) {
    var child, options,
      _this = this;
    options = [task];
    child = child_process.spawn('ant', options);
    child.stdout.on('data', function(data) {
      var buffer, line, _i, _len, _ref, _results;
      buffer = new Buffer(data);
      _ref = buffer.toString().split('\n');
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        line = _ref[_i];
        _results.push(_this.writeLine('   ant '.grey, ': '.bold.white + line));
      }
      return _results;
    });
    console.log('');
    return '';
  };

  Ant.input = function(task) {
    if (!task) {
      console.log('');
      return '';
    }
    if (task && task.length === 0) {
      console.log('');
      return '';
    }
    return this.ant(task);
  };

  Ant.run = function(argv) {
    var stdin,
      _this = this;
    stdin = process.openStdin();
    process.stdin.setRawMode(true);
    process.stdout.write(prompt + input);
    return process.stdin.on('keypress', function(chunk, key) {
      if (key) {
        if (key.ctrl && key.name === 'c') {
          process.exit();
        } else if (key.ctrl && key.name === 'd') {
          process.exit();
        } else if (key.name === 'enter') {
          input = _this.input(input);
          process.stdout.write(prompt + input);
          return;
        } else if (key.name === 'backspace') {
          input = input.slice(0, input.length - 1);
          process.stdout.clearLine();
          process.stdout.cursorTo(0);
          process.stdout.write(prompt + input);
        }
      }
      if (!chunk) {
        return;
      }
      input += chunk.toString();
      process.stdout.clearLine();
      process.stdout.cursorTo(0);
      return process.stdout.write(prompt + input);
    });
  };

  return Ant;

})();
