// Generated by CoffeeScript 1.4.0
var Build, colors, fs, hound, java;

fs = require('fs');

hound = require('hound');

colors = require('colors');

java = require('java');

module.exports = Build = (function() {

  function Build() {}

  Build.compile = function(argv, file) {
    java.classpath.push(__dirname);
    return java.callStaticMethod('noyd.compile.Compiler', 'compileErrors', file, function(err, result) {
      return console.log(result);
    });
  };

  Build.writeLine = function(line) {
    return console.log('build  - '.green + line);
  };

  Build.watchDir = function(argv, dir, callback) {
    var watcher;
    this.writeLine('watching ' + dir + ' directory for changes');
    watcher = hound.watch(dir);
    return watcher.on('change', callback);
  };

  Build.run = function(argv) {
    var _this = this;
    return fs.stat('./build.xml', function(err, stats) {
      if (err && err.code === 'ENOENT') {
        _this.writeLine('expected ./build.xml file'.bold.red);
      }
      if (err) {
        return;
      }
      return _this.watchDir(argv, './src', function(file, stats) {
        _this.writeLine('detected change file: ' + file);
        return _this.compile(argv, file);
      });
    });
  };

  return Build;

})();
