// Generated by CoffeeScript 1.4.0
var Build, colors, fs, hound;

fs = require('fs');

hound = require('hound');

colors = require('colors');

module.exports = Build = (function() {

  function Build() {}

  Build.writeLine = function(line) {
    return console.log('build  - '.green + line);
  };

  Build.watchDir = function(argv, dir, callback) {
    var watcher;
    this.writeLine('watching %s directory for changes', dir);
    watcher = hound.watch(dir);
    return watcher.on('change', callback);
  };

  Build.run = function(argv) {
    var _this = this;
    return fs.stat('./build.xml', function(err, stats) {
      if (err && err.code === 'ENOENT') {
        _this.writeLine('expected ./build.xml file'.bold.red);
      }
      if (err) {
        return;
      }
      return _this.watchDir(argv, './src', function(file, stats) {
        return _this.writeLine('detected change file: ' + file);
      });
    });
  };

  return Build;

})();
