// Generated by CoffeeScript 1.4.0
var Logcat, colors;

colors = require('colors');

module.exports = Logcat = (function() {

  function Logcat() {}

  Logcat.run = function() {
    return this.stdin();
  };

  Logcat.stdin = function() {
    process.stdin.resume();
    process.stdin.setEncoding('utf8');
    process.stdin.on('end', function() {});
    return process.stdin.on('data', function(chunk) {
      var first2, line, _i, _len, _ref, _results;
      _ref = chunk.split('\n');
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        line = _ref[_i];
        first2 = line.slice(0, 2);
        switch (first2) {
          case 'W/':
            _results.push(console.log(line.bold.red));
            break;
          default:
            _results.push(console.log(line.grey));
        }
      }
      return _results;
    });
  };

  return Logcat;

})();
