// Generated by CoffeeScript 1.4.0
var argv, children;

children = require('./children');

argv = require('optimist').usage("Filter output from adb logcat.\n\nUsage: noyd -t YourLogTag").demand('t').alias('t', 'tag').describe('t', 'Specify your adb logcat tag (to highlight)').boolean('s').alias('s', 'silent').describe('s', 'Only show matches and exceptions').argv;

module.exports = {
  run: function() {
    require('./logcat').run(argv);
    require('./build').run(argv);
    return require('./ant').run(argv);
  }
};
